"""empty message

Revision ID: 67fcba3e00b7
Revises: 
Create Date: 2024-11-13 13:57:33.707354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fcba3e00b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Submission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('share_token', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('SubmissionRecord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('remote_file_name', sa.String(length=255), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['Submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserInfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('motto', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['User.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserInfo')
    op.drop_table('SubmissionRecord')
    op.drop_table('User')
    op.drop_table('Submission')
    # ### end Alembic commands ###
